# configs/baseline.yaml
seed: 42

vectorizer:
  ngram_range: [1, 2]
  min_df: 1
  max_df: 1.0
  sublinear_tf: true

model:
  type: LinearSVC
  C: 1.0

calibration:
  enabled: false         # keep false until you have more data
  method: "sigmoid"      # "sigmoid" or "isotonic"
  cv: 3

thresholding:
  threshold: 0.5         # used later when we have probabilities
  margin_threshold: 0.20  # used now as fallback for SVM decision_function
